#!/bin/bash -f
#
# Install script for systems that are not supported by GMAO. 
# No F2PY codes will be compiled or installed
# 
#

mkdir -p install/bin
mkdir -p install/lib/Python

cd src

filelist=`ls`

for name in $filelist
do
    if [ ! -d $name ] 
    then
        if [ -x $name ] 
        then
            cp $name ../install/bin 
        fi
    fi
done

cp -r pyobs ../install/lib/Python
 
